### ISSUE TITLE
iOS Trinus Support?

### ISSUE THREAD

**Issue by jurassicjordan** [ywliu722/CS_Project-Linux_Trinus#1]
Can you add support for iOS's Trinus App?

**Comment by ywliu722** [comment]
Hi, because I just cloned this project from [other user](https://github.com/ben-romer/LinusTrinus) and modified some code to meet my research requirement. I think that you can ask the [original author](https://github.com/MyrikLD/LinusTrinus) if it is possible to support iOS's Trinus App.
